<?php
/**
 * EBANX Payment Module
 *
 */

?>

<style type="text/css">
#ebanx_installments {
    display: none;
}
#ebanx_installments table td {
    padding: 0 10px 0 0;
}
</style>

<?php if ($this->getInstallmentsActive()): ?>
<div id="ebanx_installments">
    <table>
        <tr>
            <td>Parcelas:</td>

            <td>
                <select id="ebanx_installments_number" name="ebanx[installments]">
                    <option value="1">1x <?= $this->getCurrencySymbol() ?><?= money_format("%i", $this->getPriceUpfront()) ?></option>
                    <?php for ($i = 2; $i <= $this->getMaxInstallments(); $i++): ?>
                        <option value="<?= $i ?>"><?= $i ?>x <?= $this->getCurrencySymbol() ?><?= money_format("%i", $this->getPriceInterest() / floatval($i)) ?></option>
                    <?php endfor; ?>
                </select>
            </td>

            <td>
                <select id="ebanx_installments_card" name="ebanx[installments_card]">
                    <option value="visa">Visa</option>
                    <option value="mastercard">Mastercard</option>
                </select>
            </td>
        </tr>
    </table>
</div>
<?php endif; ?>

    <script>
        var ebanxRadio = document.getElementById('p_method_ebanx')
          , ebanxInstallments = document.getElementById('ebanx_installments')
          , installmentsNumber = document.getElementById('ebanx_installments_number')
          , installmentsCard   = document.getElementById('ebanx_installments_card');

        function toggleInstallmentsCards() {
            installmentsNumber.disabled = false;
            installmentsCard.disabled = false;

            if (installmentsNumber.value == 1) {
                installmentsCard.style.display = 'none';
            } else {
                installmentsCard.style.display = 'block';
            }
        }

        function toggleInstallments() {
            if (ebanxRadio.checked == true) {
                ebanxInstallments.style.display = 'block';
            } else {
                ebanxInstallments.style.display = 'none';
            }
        }

        var paymentMethods = document.getElementsByName('payment[method]');
        for (var i = 0; i < paymentMethods.length; i++) {
            var defaultEvent = paymentMethods[i].onchange;
            paymentMethods[i].onchange = function() {
                toggleInstallments();

                if (defaultEvent) {
                    defaultEvent();
                }
            }
        }

        ebanxRadio.onclick = toggleInstallments;
        ebanxRadio.onblur  = toggleInstallments;
        installmentsNumber.onchange = toggleInstallmentsCards;

        toggleInstallmentsCards();
        setTimeout(toggleInstallmentsCards, 1000);
    </script>

<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

